-- FUNDO definition

CREATE TABLE [FUNDO] (
[CODIGO] VARCHAR(20)  UNIQUE NOT NULL,
[NOME] VARCHAR(100)  NOT NULL,
[CNPJ] VARCHAR(14)  UNIQUE NOT NULL,
[CODIGO_TIPO] INTEGER  NOT NULL,
[PATRIMONIO] NUMERIC  NULL
);


-- TIPO_FUNDO definition

CREATE TABLE [TIPO_FUNDO] (
[CODIGO] INTEGER  PRIMARY KEY NOT NULL,
[NOME] VARCHAR(20)  NOT NULL
);