// <auto-generated />
using System;
using CaseItau.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CaseItau.Infra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CaseItau.Domain.Fundos.Fundo", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("CODIGO");

                    b.Property<int>("CodigoTipo")
                        .HasColumnType("integer")
                        .HasColumnName("CODIGO_TIPO");

                    b.Property<decimal?>("Patrimonio")
                        .HasColumnType("numeric")
                        .HasColumnName("PATRIMONIO");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoTipo");

                    b.ToTable("FUNDO", (string)null);
                });

            modelBuilder.Entity("CaseItau.Domain.Fundos.TipoFundo", b =>
                {
                    b.Property<int>("CodigoTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CODIGO");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CodigoTipo"));

                    b.Property<string>("NomeTipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("NOME");

                    b.HasKey("CodigoTipo");

                    b.ToTable("TIPO_FUNDO", (string)null);
                });

            modelBuilder.Entity("CaseItau.Domain.Fundos.Fundo", b =>
                {
                    b.HasOne("CaseItau.Domain.Fundos.TipoFundo", "TipoFundo")
                        .WithMany()
                        .HasForeignKey("CodigoTipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("CaseItau.Domain.Fundos.Cnpj", "Cnpj", b1 =>
                        {
                            b1.Property<string>("FundoCodigo")
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("character varying(14)")
                                .HasColumnName("CNPJ");

                            b1.HasKey("FundoCodigo");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("FUNDO");

                            b1.WithOwner()
                                .HasForeignKey("FundoCodigo");
                        });

                    b.OwnsOne("CaseItau.Domain.Fundos.FundoNome", "Nome", b1 =>
                        {
                            b1.Property<string>("FundoCodigo")
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("NOME");

                            b1.HasKey("FundoCodigo");

                            b1.ToTable("FUNDO");

                            b1.WithOwner()
                                .HasForeignKey("FundoCodigo");
                        });

                    b.Navigation("Cnpj")
                        .IsRequired();

                    b.Navigation("Nome")
                        .IsRequired();

                    b.Navigation("TipoFundo");
                });
#pragma warning restore 612, 618
        }
    }
}
